on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1.16.2
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          color: "2105893"
          username: "Modbot Releases"
          footer_title: "[click for releases](https://github.com/BudasLounge/ModBot/releases)"
          footer_timestamp: true
          max_description: '4096'
          reduce_headings: true
